title: "Anu Agarwal"
email: anuagarwal308@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  " Data is the new future language. "
   A junior year BTech student with works in Python, Machine Learning, Data Science, and Deep Learning; I believe in leaving a mark on the artificial sciences industry someday thus continually strive for the same.
   I am keenly interested in technical works and research. 
baseurl: "/" 
url: "https://anuagarwal1409.github.io/" 
github_username:  anuagarwal1409

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-merlot
